services:
  - type: web
    name: task-manager-api
    env: node
    plan: free
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000

  - type: static
    name: task-manager-client
    env: static
    buildCommand: npm install && cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: task-manager-api
          property: url
